#!/usr/bin/env sh

# Rotate the log files
echo "\n$(date)" >>"/tmp/yabai_$USER.err.log.bak"
cat "/tmp/yabai_$USER.err.log" >>"/tmp/yabai_$USER.err.log.bak"
echo "\n$(date)" >>"/tmp/yabai_$USER.out.log.bak"
cat "/tmp/yabai_$USER.out.log" >>"/tmp/yabai_$USER.out.log.bak"
truncate -s 0 "/tmp/yabai_$USER.err.log"
truncate -s 0 "/tmp/yabai_$USER.out.log"

# Load Yabai scripting capabilities
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus off \
	focus_follows_mouse off \
	window_zoom_persist off \
	window_placement second_child \
	window_shadow float \
	window_opacity on \
	window_opacity_duration 0.2 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.95 \
	insert_feedback_color 0xff9dd274 \
	split_ratio 0.50 \
	auto_balance off \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action stack \
	top_padding 8 \
	bottom_padding 8 \
	left_padding 8 \
	right_padding 8 \
	window_gap 10
# window_animation_duration 0.5 \
# window_animation_easing ease_out_quint \

# Exclude some apps from being managed:
blacklist="$(
	cat <<EOF
Karabiner
Docker
Alfred
System Settings
Finder
Hammerspoon
1Password
Terminal
System Settings
System Information
Software Update
Dictionary
System Preferences
VLC
Calculator
Activity Monitor
Archive Utility
Parallels Desktop
EOF
)"
blacklist=$(printf '^(%s)$' "$blacklist" | tr '\n' '|')
echo "$blacklist"
yabai -m rule --add app="$blacklist" manage=off
yabai -m rule --add app="VM$" manage=off

# Enable BSP (Binary space partitioning) as default layout
yabai -m config layout bsp

echo "yabai configuration loaded"
