--
--
local M = {}

local logger = hs.logger.new("nodoz", "info")
local nodozIconOn = [[ASCII:
.....1a..........AC..........E
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
.....5c.......................
]]
local nodozIconOff = [[ASCII:
.....1a.....x....AC.y.......zE
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
...x.5c....y.......z..........
]]

local menubar

function M.setup()
	if menubar ~= nil then
		return
	end

	menubar = hs.menubar.new()
	if menubar == nil then
		logger.e("failed to create menubar item")
		return
	end

	local function setDisplay(state)
		if state then
			menubar:setIcon(nodozIconOn)
			logger.i("nodoz on")
		else
			menubar:setIcon(nodozIconOff)
			logger.i("nodoz off")
		end
	end

	menubar:setClickCallback(function()
		setDisplay(hs.caffeinate.toggle("displayIdle"))
	end)

	hs.caffeinate.set("displayIdle", true, false)
	setDisplay(true)
end

return M
